name: Autograding Tests
'on':
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: "StepTracker: constructor, addDailySteps, activeDays (30)"
        id: steptracker
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "StepTracker: constructor, addDailySteps, activeDays"
          setup-command: ''
          command: sh .github/grade.sh StepTrackerTest
          timeout: 5
          max-score: 30
      - name: "StepTracker.averageSteps (20)"
        id: averagesteps
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "StepTracker.averageSteps"
          setup-command: ''
          command: sh .github/grade.sh AverageStepsTest
          timeout: 5
          max-score: 20
      - name: "MasterMind: constructor and getHint (50)"
        id: gethint
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: "MasterMind: constructor and getHint"
          setup-command: ''
          command: sh .github/grade.sh GetHintTest
          timeout: 5
          max-score: 50
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          STEPTRACKER_RESULTS: "${{ steps.steptracker.outputs.result }}"
          AVERAGESTEPS_RESULTS: "${{ steps.averagesteps.outputs.result }}"
          GETHINT_RESULTS: "${{ steps.gethint.outputs.result }}"
        with:
          runners: steptracker,averagesteps,gethint
